name = "get-widget-docs"
type = "webpack"
account_id = "82045a407889da9f637205842a49f6ce"
workers_dev = true
route = ""
zone_id = ""
[site]
bucket = "./src/.vuepress/dist"
entry-point = "workers-site"
